# Generated by Django 5.0.1 on 2024-02-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_audio_hashcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hashcode',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
