# Generated by Django 5.0.1 on 2024-02-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_count_rating_review_mark_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='count_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='mark_count',
            field=models.IntegerField(default=0),
        ),
    ]
